### ISSUE TITLE
mod469762049の時のconvolution

### ISSUE THREAD

**Issue by ansainbdg** [shakayami/ACL-for-python#1]
convolutonにmod469762049を入れるとindex out of rangeになります。
es=[0]*24だと余裕がないので、es=[0]*30くらいにしておいた方がいいと思います。
公式C++も30確保してあります。

**Comment by shakayami** [comment]
es,ies,sum_e,sum_ieの容量を30に変更しました。これでmod469762049でも正常に動くと思います。
