### ISSUE TITLE
suffix array のバグ

### ISSUE THREAD

**Issue by NyaanNyaan** [shakayami/ACL-for-python#10]
`string.suffix_array([0, 1, 1, 1])` を呼び出すと `[0, 1, 3, 2]` が返ってきますが正しくは `[0, 3, 2, 1]` です。

デバッグしたところ、下記の箇所の `i &` を `i and` に直したら正しく動作するようになったのでこの箇所を直すとよさそうです。

https://github.com/shakayami/ACL-for-python/blob/b358cf5f81f999fa7c7006bfbe0e0e733076f3f5/string.py#L110

**Comment by shakayami** [comment]
対応しました
https://github.com/shakayami/ACL-for-python/commit/1324b7fe6c563e950c7361c90ea77179baa46f17
