### ISSUE TITLE
yosupo judgeのtwo_satがACできない

### ISSUE THREAD

**Issue by shakayami** [shakayami/ACL-for-python#2]
cycle_unsat_00.inでRuntime Errorになる。ローカルで実行してもエラーは発生しない。Runtime Errorの原因は不明だがライブラリの中にある可能性が高い。

**Comment by Rin204** [comment]
（失礼します．解決済みでしたらすみません．）
2-SATでREが出る原因ですが，yosupo judge 上での再帰回数の上限が原因だと思います．
この記事( https://tanakki-kyopro.hatenablog.com/entry/2020/09/24/012425 )はAtCoderとCodeforcesでの例ですが，sys.setrecursionlimit で変更できる上限の値の最大値が環境によって異なるみたいです．

REになっている( https://judge.yosupo.jp/submission/46165 )コード(お借りしました)のsccのdfs部分を非再帰に変更したら通りました（ https://judge.yosupo.jp/submission/79510 ）．

（細かい部分をチェックできてないので実装ミスが残ってたらごめんなさい）

**Comment by shakayami** [comment]
ありがとうございます！
pypy用として設計している以上再帰は無いほうが嬉しいので、scc,two_satを非再帰バージョンのコードに変更することにします。
